language: python

python:
  - 3.5
  - 3.6

install:
  - pip install -r requirements.txt
  - pip install tox-travis
  - python setup.py install

script:
 - tox -e py35
 - coverage run -m py.test test/test_client.py
 - coverage report -m

after_success: 
 - coverage report
